site_name: Effect Oriented Programming
site_url: https://EffectOrientedProgramming.com/
site_description: Support Site for the Book
site_author: Bill Frasure, James Ward and Bruce Eckel
# repo_url: https://github.com/EffectOrientedProgramming/book/

nav:
  - Home: index.md
  - Guide:
    - Installing Scala & Tools: guide/scalatools.md
    - Running the Book Code: guide/examples.md
  - About:
    - Authors: about/authors.md
    - License: about/license.md

plugins:
  - redirects:
      redirect_maps:
        'resources/zio/sharing-layers-between-multiple-files.md':  'https://zio.dev/reference/test/sharing-layers-between-multiple-files/'
        'resources/zio/test-assertion-library': 'https://zio.dev/reference/test/assertions/'