site_name: Effect Oriented Programming
site_url: https://EffectOrientedProgramming.com/
site_description: Support Site for the Book
site_author: Bill Frasure, James Ward and Bruce Eckel
# repo_url: https://github.com/EffectOrientedProgramming/book/

nav:
  - Home: index.md
  - Guide:
    - Installing Scala & Tools: guide/scalatools.md
    - Running the Book Code: guide/examples.md
  - About:
    - Authors: about/authors.md
    - License: about/license.md

plugins:
  - redirects:
      redirect_maps:
        # Never delete these since published books reference them
        'resources/zio/sharing-layers.md':  'https://zio.dev/reference/test/sharing-layers-between-multiple-files/'
        'resources/zio/test-assertion-library.md': 'https://zio.dev/reference/test/assertions/'
        'resources/zio/docs.md':  'https://zio.dev/reference/'
        'resources/zio/whats-functional-programming-all-about.md':  'https://www.lihaoyi.com/post/WhatsFunctionalProgrammingAllAbout.html'
        'resources/zio/zio-config-docs-index.md':  'https://github.com/zio/zio-config/blob/master/docs/index.md'
        'resources/zio/compare-and-swap.md': 'https://en.wikipedia.org/wiki/Compare-and-swap'
        'resources/zio/zio-cache.md': 'https://zio.dev/zio-cache'
        'resources/zio/ecosystem.md': 'https://zio.dev/ecosystem/'
        'resources/zio/examples/2024-09-02.md': 'https://github.com/effectorientedprogramming/examples/tree/2024-09-02'
        'resources/zio/examples/2024-09-17.md': 'https://github.com/effectorientedprogramming/examples/tree/2024-09-17'
