on: push

jobs:

  build-and-upload:
    name: build and upload
    strategy:
      matrix:
        os: [macos, ubuntu]
        include:
          - os: ubuntu
            runs-on: ubuntu-latest
            artifact-name: booker
            asset-name: booker-linux-amd64
          - os: macos
            runs-on: macos-latest
            artifact-name: booker
            asset-name: booker-macos-amd64
#          - os: windows
#            runs-on: windows-latest
#            gu-binary: gu.cmd
#            artifact-name: booker.exe
#            asset-name: booker-windows-amd64.exe
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache Coursier
        uses: coursier/cache-action@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install msvc-dev
        if: matrix.os == 'windows'
        uses: ilammy/msvc-dev-cmd@v1.9.0

      - name: Install msbuild
        if: matrix.os == 'windows'
        uses: microsoft/setup-msbuild@v1.0.2

      - name: build for windows
        if: matrix.os == 'windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          ./sbt.bat booker/graalvm-native-image:packageBin

      - name: build for linux or mac
        if: matrix.os != 'windows'
        run: |
          ./sbt booker/graalvm-native-image:packageBin

      - name: run upx on ${{ matrix.os }}
        uses: svenstaro/upx-action@v2
        with:
          file: booker/target/graalvm-native-image/${{matrix.artifact-name}}
          args: --best --lzma

#      - name: verify booker by running it
#        run: |
#          booker/target/graalvm-native-image/${{matrix.artifact-name}}

      - name: upload ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: booker-${{ matrix.os }}
          path: booker/target/graalvm-native-image/${{matrix.artifact-name}}

      - name: release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: booker/target/graalvm-native-image/${{matrix.artifact-name}}
          asset_name: ${{ matrix.asset-name }}
          tag: release-${{ github.ref }}
          overwrite: true
