on: push

jobs:

  build-and-upload:
    name: build and upload
    strategy:
      matrix:
#        os: [macos, ubuntu, windows]
        os: [windows]
        include:
#          - os: ubuntu
#            gu-binary: gu
#            artifact-name: booker
#            asset-name: booker-linux-amd64
#          - os: macos
#            gu-binary: gu
#            artifact-name: booker
#            asset-name: booker-macos-amd64
          - os: windows
            runs-on: windows-2016
            gu-binary: gu.cmd
            artifact-name: booker.exe
            asset-name: booker-windows-amd64.exe
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # todo: cache GraalVM, etc
      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ matrix.os }}-${{ hashFiles('build.sbt') }}
          restore-keys: sbt-${{ matrix.os }}-

      # todo: static image?
      - name: setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.2.0
          java: java11
          arch: amd64

      - name: install native-image
        run: ${{ matrix.gu-binary }} install native-image

      - name: Install msvc-dev
        if: matrix.os == 'windows'
        uses: ilammy/msvc-dev-cmd@v1.5.0

      - name: Install msbuild
        if: matrix.os == 'windows'
        uses: microsoft/setup-msbuild@v1

      - name: Cache Coursier
        uses: actions/cache@v2
        if: matrix.os == 'windows'
        with:
          key: coursier-cache
          path: ~\AppData\Local\Coursier\Cache\v1

      - name: Install Coursier
        if: matrix.os == 'windows'
        shell: cmd
        run: |
          bitsadmin /transfer cs-cli https://git.io/coursier-cli-windows-exe "%cd%\cs.exe"
          cs setup --yes

      - name: build for windows
        if: matrix.os == 'windows'
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          sbt graalvm-native-image:packageBin

      - name: build for linux or mac
        if: matrix.os != 'windows'
        run: |
          ./bin/sbt graalvm-native-image:packageBin

      - name: run upx on ${{ matrix.os }}
        uses: svenstaro/upx-action@v2
        with:
          file: target/graalvm-native-image/${{matrix.artifact-name}}
          args: --best --lzma

      - name: verify booker by running it
        run: |
          target/graalvm-native-image/${{matrix.artifact-name}}

      - name: upload ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: booker-${{ matrix.os }}
          path: target/graalvm-native-image/${{matrix.artifact-name}}

      - name: release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/graalvm-native-image/${{matrix.artifact-name}}
          asset_name: ${{ matrix.asset-name }}
          tag: ${{ github.ref }}
          overwrite: true