on: push

jobs:

  build-and-upload:
    name: build and upload
    strategy:
      matrix:
#        os: [macos, ubuntu, windows]
        os: [windows]
        include:
#          - os: ubuntu
#            gu-binary: gu
#            artifact-name: booker
#            asset-name: booker-linux-amd64
#          - os: macos
#            gu-binary: gu
#            artifact-name: booker
#            asset-name: booker-macos-amd64
          - os: windows
            gu-binary: gu.cmd
            artifact-name: booker.exe
            asset-name: booker-windows-amd64.exe
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # todo: cache GraalVM, etc
      - name: cache
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ matrix.os }}-${{ hashFiles('build.sbt') }}
          restore-keys: sbt-${{ matrix.os }}-

      # todo: static image?
      - name: setup GraalVM
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: 21.2.0
          java: java11
          arch: amd64

      - name: install native-image
        run: ${{ matrix.gu-binary }} install native-image

      - name: build for windows
        if: matrix.os == 'windows'
        shell: cmd
        run: |
          choco install visualstudio2017-workload-vctools
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          bitsadmin /transfer cs-cli https://git.io/coursier-cli-windows-exe "%cd%\cs.exe"
          cs setup --yes --quiet
          gu install native-image
          sbt graalvm-native-image:packageBin
      - name: build for ${{ matrix.os }}
        if: matrix.os != 'windows'
        run: |
          ./bin/sbt graalvm-native-image:packageBin

      - name: run upx on ${{ matrix.os }}
        uses: svenstaro/upx-action@v2
        with:
          file: target/graalvm-native-image/${{matrix.artifact-name}}
          args: --best --lzma

      - name: upload ${{ matrix.os }}
        uses: actions/upload-artifact@v2
        with:
          name: booker-${{ matrix.os }}
          path: target/graalvm-native-image/${{matrix.artifact-name}}
