on:
  push:
    branches:
      - main

jobs:
  gen-and-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.API_TOKEN_GITHUB }}

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'sbt'

    - run: |
        ./sbt genManuscript

    - name: Update Examples
      continue-on-error: true
      run: |
        git submodule update --init --recursive
        cd examples
        git config --global user.name 'James Ward'
        git config --global user.email 'jamesward@users.noreply.github.com'
        git add .
        git commit -m "updated examples"
        git push

    - uses: test-room-7/action-update-file@v1
      with:
        file-path: |
          manuscript/*
          manuscript/resources/images/*
        branch: publish
        commit-msg: Update manuscript
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - id: preview
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: jamesward/leanpub-actions/preview@main
      with:
        apikey: ${{ secrets.LEANPUB_APIKEY }}
        slug: effect-oriented-programming

    - id: slack-notify
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        curl -s -X POST -H 'Content-type: application/json' --data "{\"text\":\"Book Preview: ${{ steps.preview.outputs.pdf_url }} ${{ steps.preview.outputs.epub_url }}\"}" ${{ secrets.SLACK_WEBHOOK }}
