on:
  push:
    branches:
      - main

jobs:
  gen-and-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'sbt'

    - run: |
        ./sbt genManuscript

    - uses: nkoppel/push-files-to-another-repository@1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-files: 'Examples/'
        destination-username: 'EffectOrientedProgramming'
        destination-repository: 'examples'
        commit-email: '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'

    - uses: test-room-7/action-update-file@v1
      with:
        file-path: |
          manuscript/*
          manuscript/resources/images/*
        branch: publish
        commit-msg: Update manuscript
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - id: preview
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: jamesward/leanpub-actions/preview@main
      with:
        apikey: ${{ secrets.LEANPUB_APIKEY }}
        slug: effect-oriented-programming

    - id: slack-notify
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        curl -s -X POST -H 'Content-type: application/json' --data "{\"text\":\"Book Preview: ${{ steps.preview.outputs.pdf_url }} ${{ steps.preview.outputs.epub_url }}\"}" ${{ secrets.SLACK_WEBHOOK }}
