on: [push, pull_request]

jobs:
  gen-and-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

    - run: ./bin/sbt mdoc

    - id: preview
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: jamesward/leanpub-actions/preview@main
      with:
        apikey: ${{ secrets.LEANPUB_APIKEY }}
        slug: effect-oriented-programming

    - id: slack-notify
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        curl -s -X POST -H 'Content-type: application/json' --data "{\"text\":\"Book Preview: ${{ steps.preview.outputs.pdf_url }}\"}" ${{ secrets.SLACK_WEBHOOK }}
